### ISSUE TITLE
Couldn't fetch .xml RSS with images

### ISSUE THREAD

**Issue by ghost** [nek7u/FeedMoe#10]
hey, it's me. AGAIN. Your FeedMoe couldn't fetch .xml RSS with images on it i think. I tried to load [Reddit](https://www.reddit.com/hot/.xml) and [E-Hentai](https://xml.e-hentai.org/ehtracker.xml) RSS also tried re-install your skins and load [Reddit](https://www.reddit.com/hot/.xml), in the end i get error message. 

I changed my DNS to cloudflare and visit the RSS link in the browser, it load. that means ISP blocking Website is not the problem here.
![image](https://user-images.githubusercontent.com/60911510/129045578-d2001ac9-d69b-4bb5-b088-64fd1a0eefe9.png)

**Comment by nek7u** [comment]
(FeedMoe skin > right-click > Feed > Fetch Images ✔️ )
I have to say **Fetch Images** feature is **in progress**, and FeedMoe skin doesn't **FETCH** any feed images for now.
* It shows only **camera icon** if the article have an image.
* If the camera icon is clicked, open the image in the browser.

![2021-08-12_203258 902](https://user-images.githubusercontent.com/58021194/129189978-ed41d272-e106-46b9-86d4-4e47a30ba669.png)

Skin.ini < If you have a time, let me know this skin works or not.
```ini
[Variables]
@Include1=#@#Variables.inc
@Include2=#@#lang\#LANG_FILE#
@Include3=#@#FeedMoe.RSS2.inc

FEED_URL=https://www.reddit.com/r/japanpics/new/.xml
ITEM_LINK_SUBSTITUTE="(?si)^(?(?!https://(?:[0-9a-z-]+\.)?reddit\.com/).+)":""

FEED_TITLE=Japan Pics@reddit
ITEM_TITLE_SUBSTITUTE=
COLOR_BACKGROUND_HEADER_DARK=FF4500
COLOR_BACKGROUND_HEADER_LIGHT=FF4500

ITEM_IMAGE_NODE_ATTRIBUTE=url
ITEM_IMAGE_NODE_NAMESPACE=media|http://search.yahoo.com/mrss/
ITEM_IMAGE_NODE_PATH=media:thumbnail
ITEM_IMAGE_URL_SUBSTITUTE='(?si)^(?(?!https?:\/\/[^\s"<>]+$).+)':""
```
***

I also am trying to get image link from https://xml.e-hentai.org/ehtracker.xml, it failed and I have no idea why this happens yet.

Rainmeter icon > right-click > About > Skin tab > select skin name
![2021-08-12_204831 684](https://user-images.githubusercontent.com/58021194/129191706-8aedd74b-c210-486e-a1a3-ac0fb64eb60b.png)

**Comment by venya-san** [comment]
> "I have to say Fetch Images feature is in progress, and FeedMoe skin doesn't FETCH any feed images for now."
I keep that in mind.

> "Skin.ini < If you have a time, let me know this skin works or not."
Still not working. i wonder if VPN can this....
![image](https://user-images.githubusercontent.com/60911510/129202266-231dc25b-2fc4-4621-95fb-842290ce3740.png)

**Comment by ghost** [comment]
"I have to say Fetch Images feature is in progress, and FeedMoe skin doesn't FETCH any feed images for now." 
I keep that in mind.

"Skin.ini < If you have a time, let me know this skin works or not."
it seems my ISP block reddit even though i already changed my DNS... thx for your time nek.
![image](https://user-images.githubusercontent.com/60911510/129205663-d2969519-4c4b-4e05-963f-28a9e8744773.png)

**Comment by ghost** [comment]
@nek7u oh yea nek, i can hide the (1080p) and [SubsPlease] 
`ITEM_TITLE_SUBSTITUTE= "\[SubsPlease\]|\(1080p\)":""`

`![image](https://user-images.githubusercontent.com/60911510/129209547-c85f6a7a-3898-4c7c-908d-d27c5efecb32.png)
but is it possible to hide this? (what even the number mean anyway??)

**Comment by nek7u** [comment]
You can try this.
```ini
ITEM_TITLE_SUBSTITUTE="(?:\[SubsPlease\] |\s?\(1080p\)\s?|\[[[:xdigit:]]{8}\]|\.mkv$)":""
```
I guess `[DBF55DE0E]` is **CRC32**, it's for verifying the file. (MD5/SHA1/SHA256 ...)

***
[PCRE Regex Cheatsheet](https://www.debuggex.com/cheatsheet/regex/pcre)
[CRC32](https://www.google.com/search?q=CRC32&hl=en&nfpr=1&lr=lang_en) - Google search
