### ISSUE TITLE
RSS magnet feeds from subsplease.org did not appear

### ISSUE THREAD

**Issue by ghost** [nek7u/FeedMoe#8]
RSS torrent work just fine but RSS magnet link is don't and the RSS version is 2.0

RSS Main link: https://subsplease.org/rss-feeds/
Torrent feeds link (1080p): https://subsplease.org/rss/?t&r=1080
Magnet feeds link (1080p): https://subsplease.org/rss/?r=1080

**Comment by nek7u** [comment]
FeedMoe skin can have **http** or **https** links only, for security reasons.
I don't have a plan to support **magnet** links for now. So could you edit/customize the file by your self?
#### Skin.ini
```ini
[Variables]
@Include1=#@#Variables.inc
@Include2=#@#lang\#LANG_FILE#
@Include3=#@#FeedMoe.RSS2.inc

FEED_URL=https://subsplease.org/rss/?r=1080
ITEM_LINK_SUBSTITUTE="(?si)^(?(?!magnet:).+)":""

FEED_TITLE=
ITEM_TITLE_SUBSTITUTE="\[SubsPlease\] ":""
```

#### FeedMoe\\@Resources\Script.RSS2.lua (Line 140)
```lua
--		if(''~=SKIN:GetMeasure('msItemTitle'..j):GetStringValue() and string.find(SKIN:GetMeasure('msItemLink'..j):GetStringValue(), ilus)) then
		if(''~=SKIN:GetMeasure('msItemTitle'..j):GetStringValue() and (string.find(SKIN:GetMeasure('msItemLink'..j):GetStringValue(), ilus) or string.find(SKIN:GetMeasure('msItemLink'..j):GetStringValue(), 'magnet'))) then

```

![2021-08-10_232624 174](https://user-images.githubusercontent.com/58021194/128884920-f8a47146-01d3-4b45-84b2-90c4e30a8978.png)

**Comment by ghost** [comment]
yea sure. i don't know how to modify the file to show the magnet links, thx. 
and one more thing... could i create new issues for feature request (i have 2 things in mind)?

**Comment by nek7u** [comment]
Feel free to create new issue. Keep in mind, if you have **2** feature requests, then create **2** issues.
